spring.application.name=PostService
server.port=8002
spring.cloud.consul.discovery.hostname=
spring.cloud.consul.discovery.ip-address=192.168.1.3
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=2s
management.endpoints.web.exposure.include=health,info,metrics
logging.level.org.springframework.cloud.consul=DEBUG
server.forward-headers-strategy=framework
spring.datasource.url=jdbc:postgresql://localhost:5432/posts
spring.datasource.username=postgres
spring.datasource.password=Ansal@01
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect