spring.application.name=AuthService
spring.data.mongodb.uri=mongodb://localhost:27017/google_login
server.port=8001
spring.cloud.consul.discovery.prefer-ip-address=false
spring.cloud.consul.discovery.hostname=host.docker.internal
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=2s
management.endpoints.web.exposure.include=health,info,metrics
logging.level.org.springframework.cloud.consul=DEBUG
server.forward-headers-strategy=framework

# OAuth2 Client Configuration for Google
spring.security.oauth2.client.registration.google.client-id=120623975177-n2fc92mb66h1ddrkgauu5ir6tq33c6k5.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
